# Curso Deep Learning - Exercício pré-curso Python - NumPy

Este é um notebook Jupyter contendo exercícios de programação matricial utilizando o Python e biblioteca NumPy.
Estes exercícios servem para familiarizar o participante na linguagem Python para manipulação matricial.

Esta lista de exercício é um guia de estudo. Para fazer os exercícios será necessário estudar o Python, consultar documentação e tutoriais disponíveis na Internet.

Estes exercícios são de dificuldade **intermediária para difícil**, usaremos programação
avançada Python, explorando listas, dicionários, programação matricial e programação
orientada a objeto.

### Python

O curso será feito utilizando a versão Python 3.6, assim recomenda-se que estes exercícios sejam feitos com o Python 3.
Recomenda-se instalar o Jupyter e o Python utilizando-se o [Anaconda](https://www.continuum.io/downloads) - uma distribuição
focada em Data Science, contendo os principais pacotes usados nesta área.

### Jupyter notebook

Este é um Notebook Jupyter. Um notebook Jupyter é uma mistura de linguagem Markdown para formatar texto (como uma Wiki) e um programa Python. É muito usado entre as pessoas que trabalham com Data Science e Machine Learning em Python. Se você precisar de ajuda sobre como usar os Notebooks Jupyter, veja [beginner-guide](https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/).

Instale o Jupyter nbextensions que é um conjunto de ferramentas auxiliares. Habilite o "Table of Contents" do nbextensions para que este notebook fique itemizado.

Você pode adicionar quantas células quiser neste notebook para deixar suas respostas bem organizadas.

# Exercícios básicos

Vamos começar! Comece imprimindo seu nome e e-mail aqui:

In [1]:
# preencha com seus dados
print('My name is Adriano Orsoni Diniz')
print('My email is adordi@gmail.com')

My name is Adriano Orsoni Diniz
My email is adordi@gmail.com


## Listas

Iremos utilizar muitas listas no curso Deep Learning.
Seguem alguns exercícios com lista. Python é muito bom para processar listas. Uma lista é uma sequência de elementos 
separados por vírgula dentro de chaves:

In [2]:
mylist = [5, 8, 'abc', 0, 8.3]

### Imprimindo o número de elementos de uma `mylist` e alguns de seus elementos

In [3]:
print(len(mylist))
print(mylist[0])
print(mylist[-1])  # observe o índice -1

5
5
8.3


O que o índice -1 significa?

O índice -1 aponta para o último elemento da lista.

## Seja uma lista de 10 elementos numéricos sequenciais, começando em zero

O código a seguir é típico para criar uma lista com os 10 primeiros inteiros maiores ou iguais a zero: inicializa-se lista vazia, para cada i entre 0 e menor que 10, faz append na lista a:

In [4]:
a = []
for i in range(10):
    a.append(i)
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Outra forma de criar a lista a partir da função *range* é passando a mesma como argumento para a função *list*:

In [5]:
r = range(10)
print(f'Range r: {r}')
print(f'Tipo de r: {type(r)}')
l = list(range(10))
print(f'Lista l: {l}')
print(f'Tipo de l: {type(l)}')

Range r: range(0, 10)
Tipo de r: <class 'range'>
Lista l: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Tipo de l: <class 'list'>


## List Comprehension

Esta mesma lista pode ser criada utilizando a construção denominada "List Comprehension" ou
"Compreensão de Lista" em português. Coloque este termo no Google adicionando python na frente na forma:
"python comprehension list" e você poderá ver vários exemplos e tutoriais sobre o assunto. É uma forma compacta que fazer um append iterativo numa lista:

Veja como o trecho acima foi reduzido para uma linha apenas:

In [6]:
a = [i for i in range(10)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [7]:
m_list = ['r', 'i', 'c', 'a', 'r', 'd', 'o']
new_list = []
for k,i in enumerate(m_list):
    new_list.append(str(k)+i)
print(new_list)

['0r', '1i', '2c', '3a', '4r', '5d', '6o']


- Explique o que o enumerate faz no programa acima:

A função *enumerate* itera sobre a lista usada como seu argumento, retornando elemento a elemento juntamente com o índice do elemento (número inteiro da posição na lista, iniciando em 0).

- Repita o mesmo exercício de criar a lista new_list, porém utilizando list comprehension:
   

In [8]:
m_list = ['r', 'i', 'c', 'a', 'r', 'd', 'o']
n_list = [str(i)+m_list[i] for i in range(len(m_list))]
print(n_list)

['0r', '1i', '2c', '3a', '4r', '5d', '6o']


## Fatiamento em Python

Um conceito fundamental em Python é o do fatiamento "slicing", em inglês. É um conceito que será muito usado
durante todo o curso. Estude bem isso. Inicialmente iremos trabalhar com fatiamento de lista, mas posteriormente
com arrays (ou tensores) utilizando o NumPy

In [9]:
print(a[3:5])

[3, 4]


### Criar e imprimir uma lista a partir da lista "a" já criada, porém apenas alguns elementos

Imprima os elementos ímpares de a:

In [10]:
print(a[1::2])

[1, 3, 5, 7, 9]


Imprima os elementos pares de a:

In [11]:
print(a[::2])

[0, 2, 4, 6, 8]


Imprima os últimos 3 elementos da lista (utilize índice negativo, pesquise na Internet):

In [12]:
print(a[-3:])

[7, 8, 9]


Imprima os 3 primeiros elementos da lista (veja quando é possível ignorar valores iniciais e finais):

In [13]:
print(a[:3])

[0, 1, 2]


Veja o significado do passo: dar a distância e a direção dos elementos amostrados da lista

In [14]:
print(a[::2])
print(a[::-1])

[0, 2, 4, 6, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


Imprima os elementos ímpares na order reversa, do maior para o menor:

In [15]:
print(a[-1::-2])

[9, 7, 5, 3, 1]


## Tuplas

Dominar o conceito de tuplas é importante pois tuplas são estruturas muito utilizadas no Python.

In [16]:
b = tuple(a)
print(b)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


A principal diferença entre uma lista e uma tupla é que a lista é um objeto **'mutável'**, ou seja, após instanciado pode ser alterado (um elemento pode ser removido ou adicionado à lista). A tupla, ao contrário, é um objeto **'imutável'**, podendo inclusive ser usada como uma referência única (por exemplo uma chave de dicionário).

# Dicionários em Python

Python possui uma estrutura de dados muito versátil denominada dicionário.
No curso Deep Learning, os parâmetros da rede neural serão armazenadas na forma de dicionário.

In [17]:
rob_record = {'nome': 'Roberto', 'idade': 18}
print(rob_record['nome'])

Roberto


In [18]:
rob_record['idade'] = 20
print(rob_record)

{'nome': 'Roberto', 'idade': 20}


Lista de dicionários:

In [19]:
records = [{'nome':'Alfredo', 'idade': 23},
           {'nome':'Fernanda', 'idade': 16},
           {'nome':'Carla', 'idade':33}]

Acesse o nome da Fernanda:

In [20]:
print(records[1]['nome'])

Fernanda


Crie uma lista com todos os nomes da lista records. O resultado deve ser uma lista ['Alfredo', 'Fernanda', 'Carla']

**1**. Utilizando a forma tradicional de criar lista com append:

In [21]:
nlist = []
for entry in records:
    nlist.append(entry['nome'])
print(nlist)

['Alfredo', 'Fernanda', 'Carla']


**2**. Utilizando a forma de list comprehension:

In [22]:
nlist2 = [entry['nome'] for entry in records]
print(nlist2)

['Alfredo', 'Fernanda', 'Carla']


# Exercícios usando NumPy

Os seguintes exercícios devem usar apenas o pacote NumPy.
Não se deve utilizar nenhum outro pacote adicional.
O NumPy é o pacote em Python apropriado para programação científica.
A programação eficiente de matrizes multidimensionais (arrays ou tensores) é
feita através do conceito de programação matricial que evita o uso de laços
e iterações nos elementos da matriz.

Existem vários exemplos de uso de NumPy no conjunto de
notebooks tutorias disponíveis no GitHub:
- https://github.com/robertoalotufo/ia898/blob/master/master/0_index.ipynb

In [23]:
import numpy as np

In [24]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
A = np.arange(24).reshape(4,6)
print(A)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


### rows, cols, dimensions, shape and datatype

Imprima o número de linhas de A:

In [26]:
print(f'# de linhas de A: {A.shape[0]}')

# de linhas de A: 4


Imprima o número de colunas de A:

In [27]:
print(f'# de colunas de A: {A.shape[1]}')

# de colunas de A: 6


Imprima o número de dimensões de A:

In [28]:
print(f'# de dimensões de A: {len(A.shape)}')

# de dimensões de A: 2


Imprima o shape de A:

In [29]:
print(f'Shape de A: {A.shape}')

Shape de A: (4, 6)


Imprima o tipo de dados (dtype) dos elementos de A:

In [30]:
print(f'Tipo de dados (dtype) dos elementos de A: {A.dtype}')

Tipo de dados (dtype) dos elementos de A: int64


### Reshape

Seja o vetor unidimensional a:

In [31]:
a = np.array([1,2,3,4])
print(a, a.shape)

[1 2 3 4] (4,)


Converta o vetor unidimensional a em uma matriz vetor coluna (4 linhas e 1 coluna) utilizando reshape:

In [32]:
a = a.reshape(4, 1)
print(f'a:\n{a}')
print(f'Shape de a: {a.shape}')

a:
[[1]
 [2]
 [3]
 [4]]
Shape de a: (4, 1)


## Operações aritméticas

In [33]:
B = A + 10
B

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33]])

### Array binário (booleano)

Crie uma matriz booleana C com True nos elementos de B menores que 18 (não utilize loop explícito):

In [34]:
C = B < 18
print(C)

[[ True  True  True  True  True  True]
 [ True  True False False False False]
 [False False False False False False]
 [False False False False False False]]


## Indexação booleana

Veja um programa que cria matriz D_loop a partir da matriz B, porém trocando os elementos menores que 18 por seus valores negativos

In [35]:
D_loop = B.copy()
for row in np.arange(B.shape[0]):
    for col in np.arange(B.shape[1]):
        if B[row,col] < 18:
            D_loop[row,col] = - B[row,col]
print(D_loop)

[[-10 -11 -12 -13 -14 -15]
 [-16 -17  18  19  20  21]
 [ 22  23  24  25  26  27]
 [ 28  29  30  31  32  33]]


### Troque o programa acima por uma única linha sem loop

In [36]:
D = (B < 18) * (-B) + (B >= 18) * B
print(D)

[[-10 -11 -12 -13 -14 -15]
 [-16 -17  18  19  20  21]
 [ 22  23  24  25  26  27]
 [ 28  29  30  31  32  33]]


In [37]:
B[B>18]= - B[B>18]
B

array([[ 10,  11,  12,  13,  14,  15],
       [ 16,  17,  18, -19, -20, -21],
       [-22, -23, -24, -25, -26, -27],
       [-28, -29, -30, -31, -32, -33]])

## Redução de eixo: soma

Operações matriciais de redução de eixo são muito úteis e importantes.
É um conceito importante da programação matricial.

Estude o exemplo a seguir:

In [38]:
print(f'A:\n{A}')
print(f'Shape de A: {A.shape}')

A:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Shape de A: (4, 6)


In [39]:
print(f'Valor medio de A: {A.mean()}')

Valor medio de A: 11.5


In [40]:
As = A.sum(axis=0)
print(f'As: {As}')
print(f'Shape de As: {As.shape}')
print(f'# de dimensoes de As: {len(As.shape)}')

As: [36 40 44 48 52 56]
Shape de As: (6,)
# de dimensoes de As: 1


In [41]:
Ap = A.sum(axis=1)
print(f'Ap: {Ap}')
print(f'Shape de As: {Ap.shape}')
print(f'# de dimensoes de Ap: {len(Ap.shape)}')

Ap: [ 15  51  87 123]
Shape de As: (4,)
# de dimensoes de Ap: 1


Seja a matriz $C$ que é a normalização da matriz $A$:
$$ C(i,j) = \frac{A(i,j) - A_{min}}{A_{max} - A_{min}} $$

Em programação matricial, não se faz o loop em cada elemento da matriz,
mas sim, utiliza-se operações matriciais. Faça o exercício a seguir
sem utilizar laços explícitos:

Criar a matriz C que é a normalização de A, de modo que os valores de C estejam entre 0 e 1

In [42]:
C = (A - A.min()) / (A.max() - A.min())
print(C)

[[ 0.          0.04347826  0.08695652  0.13043478  0.17391304  0.2173913 ]
 [ 0.26086957  0.30434783  0.34782609  0.39130435  0.43478261  0.47826087]
 [ 0.52173913  0.56521739  0.60869565  0.65217391  0.69565217  0.73913043]
 [ 0.7826087   0.82608696  0.86956522  0.91304348  0.95652174  1.        ]]


Modificar o exercício anterior, porém agora faça a normalização para cada coluna de A de modo que as colunas da matriz D estejam entre os valores de 0 a 1.

In [43]:
# Dica: utilize o conceito de redução de eixo
D = (A - A.min(axis=0)) / (A.max(axis=0) - A.min(axis=0))
print(D)

[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.33333333  0.33333333  0.33333333  0.33333333  0.33333333  0.33333333]
 [ 0.66666667  0.66666667  0.66666667  0.66666667  0.66666667  0.66666667]
 [ 1.          1.          1.          1.          1.          1.        ]]


## Fatiamento em arrays (slicing)

Esta indexação é chamada fatiamento:

In [44]:
AA = A[:,1::2]
print(AA)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]]


Crie a matriz AB apenas com as linhas pares da matriz A, utilizando o conceito de fatiamento:

In [45]:
AB = A[::2,:]
print(AB)

[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]


Crie a matriz AC com mesmo shape da matriz A, porém com os elementos na ordem inversa trocando a ordem das linhas e das colunas

In [46]:
AC = A[-1::-1,-1::-1]
print(AC)

[[23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]


## Produto matricial  (dot product)

Calcule a matriz E dada pelo produto matricial entre a matriz A e sua transposta: 
$$ E = A A^T $$

In [47]:
E = A.dot(A.T)
print(E)

[[  55  145  235  325]
 [ 145  451  757 1063]
 [ 235  757 1279 1801]
 [ 325 1063 1801 2539]]


Descomente a linha e explique porquê a operação de multiplicação dá erro:

In [48]:
Ee = A * A.T

ValueError: operands could not be broadcast together with shapes (4,6) (6,4) 

O erro ocorre porque o operador __*__ computa uma multiplicação elemento a elemento, pareados pelos índices da posição (linha e coluna). Dado que as matrizes A e A.T tem dimensões diferentes, esse pareamento não é possível.

## Matrizes multidimensionais

Em deep learning, iremos utilizar matrizes multidimensionais
que são denominados como arrays no NumPy. PyTorch usa o nome de tensor para
suas matrizes multimensionais.

Matrizes de dimensões maior que 4 são de difícil intuição. A melhor forma de lidar
com elas é observando o seu *shape*.

### 3-D array

In [49]:
F = A.reshape(2,3,4)
print(F)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


#### Indexação

Estude e explique as seguintes indexações:

In [50]:
print('Com um indice:\n', F[1])
print('Com dois indices:', F[1,0])
print('Com tres indices:', F[1,0,2])

Com um indice:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Com dois indices: [12 13 14 15]
Com tres indices: 14


As três indexações são diferentes pelo número de índices (1, 2 e 3, respectivamente), levando a porções de diferentes tamanhos da matriz **F**. A soma do número de índices utilizados e do número de dimensões da matriz resultante deve ser sempre 3 (o número de dimensões de **F**). Assim, com apenas 1 índice (primeiro exemplo), tem-se como retorno uma matriz de dimensão 2. Para o segundo exemplo, o retorno é uma linha apenas. Para o terceiro exemplo, tem-se o valor numérico do campo em uma posição determinada.

Imprima o número de dimensões e o shape de F:

In [51]:
print(f'# de dimensoes de F: {len(F.shape)}')
print(f'Shape de F: {F.shape}')

# de dimensoes de F: 3
Shape de F: (2, 3, 4)


## Redução de eixo - aplicado a dois eixos simultâneos

Redução de eixo é quando a operação matricial resulta num array de menores dimensões.
Com essas operações, calcula-se estatística de colunas, linhas, etc.

Calcule o valor médio das matrizes F[0] e F[1], com apenas um comando usando *F.mean()*

In [52]:
print(F.mean(axis=(1, 2)))

[  5.5  17.5]


## Broadcasting

O que significa o conceito de broadcasting em NumPy?

Broadcasting em NumPy significa expandir uma matriz em uma ou mais de suas dimensões, replicando seus elementos nessas dimensões, a fim de alcançar a dimensão necessária para a realização de uma operação matricial.

Usando o conceito de broadcast, mude o shape do vetor a para que o broadcast possa ocorrer em G = A + a

In [53]:
a = np.arange(4)
print(a)
G = A + a.reshape(4, 1)
print(G)

[0 1 2 3]
[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]
 [21 22 23 24 25 26]]


## Function - split - dados treino e validação

O exercício a seguir é para separar um conjunto de dados (dataset) em dois conjuntos, um
de treinamento e outro de validação.


Defina uma função que receba como entrada uma matriz, (dataset), onde cada linha é
referente a uma amostra e cada coluna referente a um atributo das amostras. O número total de
amostras é dado pelas linhas desta matriz.
Outro parâmetro de entrada é o fator de split `split_factor`, que é um número real entre 0 e 1. 
A saída da função são duas matrizes: amostras de treinamento e amostras de validação. 
A matriz de treinamento conterá o número de linhas dado por `split_factor` vezes o número de amostras.
A matriz de validação conterá o restante das amostras.

In [54]:
# Entrada, matriz contendo 10 amostras e 9 atributos
aa = np.arange(90).reshape(10,9)
print(aa)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


In [55]:
# Saída da função t,v = split(aa, 0.8)  # utilizado split_factor de 80%
t = np.arange(72).reshape(8,9)
print(t)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]


In [56]:
v = np.arange(72,90).reshape(2,9)
print(v)

[[72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


Evite o uso de laço explícito e não utilize outras bibliotecas além do NumPy:

In [57]:
def split(dados, split_factor):
    '''
    divide a matriz dados em dois conjuntos:
    matriz train: split_factor * n. de linhas de dados
    matriz val: (1-split_factor) * n. de linhas de dados
    parametros entrada:
        dados: matriz de entrada
        split_factor: entre 0. e 1. - fator de divisão em duas matrizes
    parametros de saída:
        train : matriz com as linhas iniciais de dados
        val: matriz com as linhas restantes
    '''
    split_line = round(split_factor * dados.shape[0])
    train = dados[:split_line,:]
    val = dados[split_line:,:]
    return train, val

In [58]:
t,v = split(aa, 0.8)
print('t=\n', t)
print('v=\n', v)

t=
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]
v=
 [[72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


Teste sua função com outros valores:

In [59]:
aa2 = np.arange(144).reshape(12,12)
print(aa2)
t2,v2 = split(aa2, 0.7)
print('t2=\n', t2)
print('v2=\n', v2)

[[  0   1   2   3   4   5   6   7   8   9  10  11]
 [ 12  13  14  15  16  17  18  19  20  21  22  23]
 [ 24  25  26  27  28  29  30  31  32  33  34  35]
 [ 36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71]
 [ 72  73  74  75  76  77  78  79  80  81  82  83]
 [ 84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107]
 [108 109 110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131]
 [132 133 134 135 136 137 138 139 140 141 142 143]]
t2=
 [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80 81 82 83]
 [84 85 86 87 88 89 90 91 92 93 94 95]]
v2=
 [[ 96  97  98  99 100 101 102 103 104 105 106 107]
 [108 109 110

In [60]:
aa3 = np.arange(98).reshape(14,7)
print(aa3)
t3,v3 = split(aa3, 0.6)
print('t3=\n', t3)
print('v3=\n', v3)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76]
 [77 78 79 80 81 82 83]
 [84 85 86 87 88 89 90]
 [91 92 93 94 95 96 97]]
t3=
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]]
v3=
 [[56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76]
 [77 78 79 80 81 82 83]
 [84 85 86 87 88 89 90]
 [91 92 93 94 95 96 97]]


# Programação Orientada a Objetos

Documentação oficial: https://docs.python.org/3/tutorial/classes.html

Forma clássica de definição de uma função:

In [61]:
data = np.array([13, 63, 5, 378, 58, 40])

def avg(d):
    return sum(d)/len(d)
    
avg(data)

92.833333333333329

## Definição da classe, variáveis, inicialização e método

Definição da classe `MyAvg`, contendo duas variávels: `id` (compartilhada) e `d`; inicialização e método `avg`.

- **Classe** é uma forma de definir um tipo abstrato de dados
- **Instância** de uma classe é chamada **objeto**
- Operadores ou funções de uma classe são chamados **métodos**
- **Variáveis de instância** são variáveis associadas à instância
- **Variáveis de classe** são variáveis compartilhadas com todas as instâncias da classe

O nome de uma classe é usualmente escrita usando *Camel case* enquanto que métodos são
escritos com caixa baixa.

In [62]:
class MyAvg:
    id = 0.33                # variável compartilhada com todas as instâncias
    
    def __init__(self,data):
        self.d = data        # variável associada a cada instância 
        
    def avg(self): # método para calcular a média
        return sum(self.d)/len(self.d)

Objetos `a` e `b` são instâncias da classe `MyAvg`.
Instanciar uma classe é inicializá-la através da chamada ao método __init__:

In [63]:
a = MyAvg(data)
b = MyAvg(2*data)

Aplicação do método `avg()`, retorna a média dos dados dos objetos a e b:

In [64]:
print(a.avg())
print(b.avg())

92.8333333333
185.666666667


Imprima os valores dos dados associados aos objetos a e b:

In [65]:
print(f'Dado associado ao objeto a: {a.d}')
print(f'Dado associado ao objeto b: {b.d}')

Dado associado ao objeto a: [ 13  63   5 378  58  40]
Dado associado ao objeto b: [ 26 126  10 756 116  80]


Imprima a variável compartilhada `id` de cada objeto a e b:

In [66]:
print(f'Variavel compartilhada no objeto a: {a.id}')
print(f'Variavel compartilhada no objeto b: {b.id}')

Variavel compartilhada no objeto a: 0.33
Variavel compartilhada no objeto b: 0.33


## Herança de classe

In [67]:
class MyAvgStd(MyAvg):
    def var(self):
        """
        Método adicional para calcular a variância
        """
        u = self.avg()
        return np.sqrt(np.sum((self.d - u)**2)/len(self.d))

In [68]:
c = MyAvgStd(data)

In [69]:
print('media:',c.avg())
print('variancia:',c.var())

media: 92.8333333333
variancia: 129.29477518


Imprima os dados associados ao objeto c e a sua variável compartilhada id:

In [70]:
print(f'Dado associado ao objeto c: {c.d}')
print(f'Variavel compartilhada no objeto c: {c.id}')

Dado associado ao objeto c: [ 13  63   5 378  58  40]
Variavel compartilhada no objeto c: 0.33


### Exercício: convertendo a função `split` na classe `C_Split`

Implemente a classe `C_Split` para ter a mesma funcionalidade da função `split` feita acima

In [71]:
class C_Split():
    def __init__(self,d):
        self.dados = d

    def split(self, split_factor):
        split_line = round(split_factor * self.dados.shape[0])
        train = self.dados[:split_line,:]
        val = self.dados[split_line:,:]

        return train, val

In [72]:
data_train_val = C_Split(aa)
train, val = data_train_val.split(0.8)
print('train:\n', train)
print('val:\n', val)

train:
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]
val:
 [[72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


## Classe com métodos `__len__` e `__getitem__`

Uma classe com métodos `__len__` e `__getitem__` permite que os objetos possam ser indexados e calculado o seu número de elementos.

Veja o exemplo a seguir:

In [73]:
class Word():
    def __init__(self, phrase):
        self.wordlist = phrase.split()
    
    def __len__(self):
        return len(self.wordlist)
    
    def __getitem__(self,x):
        return self.wordlist[x]

Separa uma frase em uma lista de palavras:

In [74]:
frase = 'Esta frase é formada por 7 palavras'
palavras = Word(frase)

Permite a indexação do objeto:

In [75]:
palavras[3]

'formada'

In [76]:
print(len(palavras))

7


### Exercício para indexar elementos de um dicionário

Um dicionário em Python não é indexado. Por exemplo seja o dicionário `d` a seguir.
Não é possível indexar d[0] ou d[1] para buscar o primeiro ou segundo par (chave:valor).

In [77]:
d = {'a':1,'b': 2}

Implementar uma classe que receba um dicionário e permita que ele possa ser indexado.
Para converter um dicionário em uma lista de pares, use:

In [78]:
list(d.items())

[('a', 1), ('b', 2)]

Complete a definição da classe `dicdata` a seguir para que um dicionário possa ser
indexado:

In [79]:
class DicData():
    def __init__(self, dic):
        self.dic_list = list(dic.items())

    def __len__(self):
        return(len(self.dic_list))
        
    def __getitem__(self, x):
        return self.dic_list[x]

In [80]:
dd = DicData(d)
print(f'Comprimento de dd: {len(dd)}')
print(f'Primeiro elemento de dd: {dd[0]}')

Comprimento de dd: 2
Primeiro elemento de dd: ('a', 1)


## Iteradores

Iteradores são uteis para serem usados em estruturas do tipo `for a in b:`.

Listas em Python são consideradas iteráveis, pois podem ser utilizadas nessa estrutura:

In [81]:
for i in ['a', 'b', 'c']:
    print(i)

a
b
c


O método do `range()` do python também é um iterável:

In [82]:
for i in range(3):
    print(i)

0
1
2


É possível acessar o iterador destas estruturas utilizando o método `iter()` do Python e então é possível percorrer seus elementos utilizado `next()`:

In [83]:
lista = ['a', 'b', 'c']
iterador = iter(lista)
print('tipo de iterador:', type(lista))
print('tipo de iterador:', type(iterador))
print(next(iterador))

tipo de iterador: <class 'list'>
tipo de iterador: <class 'list_iterator'>
a


O acesso de iteradores é sequencial e após o ultimo elemento uma exceção é levantada indicando o fim do iterador.
Descomente o último `next` e veja o tipo da exceção que acontece.

In [84]:
print(next(iterador))
print(next(iterador))
print(next(iterador))

b
c


StopIteration: 

## Criando objetos iteráveis

Para implementar um objeto iterador é preciso escrever um método `__next__()` para a classe e para que ele seja acessível como iterável também é necessário escrever um método `__iter__()`: 

In [85]:
class WordIterator():
    def __init__(self, phrase):
        self.words = phrase.split()
        
    def __iter__(self):
        self.iter_index = 0
        return self
    
    def __next__(self):
        if self.iter_index < len(self.words):
            i = self.iter_index
            self.iter_index += 1
            return self.words[i]
        else:
            raise StopIteration()

A classe acima é um iterador e é iterável. 

No método `__iter__()` reiniciamos o índice inicial para o iterador e retornamos o próprio objeto (um iterador).

No método `__next__()` retornamos a palavra do índice atual ou a exceção de parada, caso seja o fim.

In [86]:
frase = 'Esta frase é formada por 7 palavras'
iterador_de_palavras = WordIterator(frase)

In [87]:
for palavra in iterador_de_palavras:
    print(palavra)

Esta
frase
é
formada
por
7
palavras


### Exercício com iterador

Crie uma classe `DictIterator` que permita varrer os itens de um dicionário utilizando o `for`

In [88]:
class DictIterator():
    def __init__(self, dic):
        self.dic_list = list(dic.items())

    def __iter__(self):
        self.iter_idx = 0
        return self

    def __next__(self):
        if self.iter_idx >= len(self.dic_list):
            raise StopIteration()
        else:
            cur_idx = self.iter_idx
            self.iter_idx += 1

            return self.dic_list[cur_idx]

In [89]:
d = {'a':1,'b': 2, 'c': 3}
d_iter = DictIterator(d)
for i in d_iter:
    print(i)

('a', 1)
('b', 2)
('c', 3)


## Objeto como função

É possível declarar uma classe contendo um objeto que possa ser chamado (*callable object*).
Para isso, a classe deve conter o método `__call__`. Veja o exemplo a seguir:

In [90]:
class Scale():
    def __init__(self, w):
        self._w = w
    def __call__(self, x):
        return x * self._w

In [91]:
s = Scale(100.)
print(s(5))


500.0


### Exercício de classe contendo objeto chamável

Defina uma classe herdada da classe `Scale` que permita modificar a variável `self._w`.

In [92]:
class AjustaPeso(Scale):
    def wset(self, new_w):
        self._w = new_w

In [93]:
ap = AjustaPeso(100.)
print(ap(5))

500.0


In [94]:
ap.wset(10)
print(ap(5))

50


# Fim do notebook